In [1]:
import torch
x = torch.rand(5, 3)
print(x)

tensor([[0.4380, 0.1670, 0.2661],
        [0.4583, 0.9636, 0.0159],
        [0.8425, 0.0500, 0.7868],
        [0.6252, 0.6481, 0.4173],
        [0.9061, 0.1485, 0.4324]])


In [2]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Device: {device}")

Device: cuda


In [3]:
x = torch.rand(5, 3)
print(x)


tensor([[0.0333, 0.3413, 0.9212],
        [0.7802, 0.6631, 0.1979],
        [0.3430, 0.3202, 0.3345],
        [0.6660, 0.9757, 0.7660],
        [0.1685, 0.5206, 0.1891]])


In [5]:
x = torch.randn(3, 3).to(device)

In [6]:
x

tensor([[-1.0506,  0.0121,  0.2039],
        [-0.4793,  1.0194,  0.8467],
        [ 0.4157,  0.7538, -1.9260]], device='cuda:0')

In [7]:
print(x)

tensor([[-1.0506,  0.0121,  0.2039],
        [-0.4793,  1.0194,  0.8467],
        [ 0.4157,  0.7538, -1.9260]], device='cuda:0')
