In [1]:
import torch
x = torch.rand(5, 3)
print(x)

tensor([[0.7263, 0.7876, 0.6878],
        [0.9298, 0.4113, 0.6065],
        [0.0846, 0.0541, 0.8838],
        [0.1843, 0.8298, 0.6794],
        [0.7248, 0.2675, 0.8164]])


In [2]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Device: {device}")

Device: cuda


In [3]:
x = torch.rand(5, 3)
print(x)


tensor([[0.1610, 0.5761, 0.6652],
        [0.5641, 0.3933, 0.5091],
        [0.2464, 0.0985, 0.9927],
        [0.0905, 0.5790, 0.8011],
        [0.8089, 0.3745, 0.2886]])


In [4]:
x = torch.randn(3, 3).to(device)

In [5]:
x

tensor([[ 0.2393, -0.5581, -1.1047],
        [-0.6415,  0.4365, -0.0180],
        [-1.6712,  0.7361, -0.0234]], device='cuda:0')

In [6]:
print(x)

tensor([[ 0.2393, -0.5581, -1.1047],
        [-0.6415,  0.4365, -0.0180],
        [-1.6712,  0.7361, -0.0234]], device='cuda:0')
